export enum EStandardServiceCategory {
    CONTRACTOR = 'CONTRACTOR',
    DESIGNER = 'DESIGNER',
    REALTOR = 'REALTOR',
    ENGINEER = 'ENGINEER',
    LENDER = 'LENDER',
    INSPECTOR = 'INSPECTOR',
    LANDSCAPER = 'LANDSCAPER',
    PLUMBER = 'PLUMBER',
    ELECTRICIAN = 'ELECTRICIAN',
    ARCHITECT = 'ARCHITECT',
    PROPERTY_MANAGER = 'PROPERTY_MANAGER',
    APPRAISER = 'APPRAISER',
}
